### ISSUE TITLE
run-script for the update of the webdriver-manager didn't work with windows 7

### ISSUE THREAD

**Issue by JanOschii** [NathanWalker/angular-seed-advanced#105]
**Steps to reproduce and a minimal demo of the problem**
1) Use a computer with windows 7 ( ;) )
2) Enter: `npm run webdriver-update`

**Current behavior**

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "webdriv
er-update"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 webdriver-update: `node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 webdriver-update script 'node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webdriver-update' ]
2 info using npm@3.8.8
3 info using node@v6.2.0
4 verbose run-script [ 'prewebdriver-update',
4 verbose run-script   'webdriver-update',
4 verbose run-script   'postwebdriver-update' ]
5 info lifecycle angular2-seed-advanced@0.0.0~prewebdriver-update: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~prewebdriver-update: no script for prewebdriver-update, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~webdriver-update: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~webdriver-update: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~webdriver-update: PATH: ...
10 verbose lifecycle angular2-seed-advanced@0.0.0~webdriver-update: CWD: C:\Users\Admin\.docker.projects\nginx-php-fpm-phalcon\www\front04
11 silly lifecycle angular2-seed-advanced@0.0.0~webdriver-update: Args: [ '/d /s /c',
11 silly lifecycle   'node_modules/protractor/bin/webdriver-manager update' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~webdriver-update: Returned: code: 1  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~webdriver-update: Failed to exec webdriver-update script
14 verbose stack Error: angular2-seed-advanced@0.0.0 webdriver-update: `node_modules/protractor/bin/webdriver-manager update`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd C:\Users\Admin\{...}
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "webdriver-update"
19 error node v6.2.0
20 error npm  v3.8.8
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 webdriver-update: `node_modules/protractor/bin/webdriver-manager update`
22 error Exit status 1
23 error Failed at the angular2-seed-advanced@0.0.0 webdriver-update script 'node_modules/protractor/bin/webdriver-manager update'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node_modules/protractor/bin/webdriver-manager update
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Workaround**

Just type: `node_modules/protractor/bin/webdriver-manager update` instead of `npm run webdriver-update` which at the end should do the same.

**Comment by NathanWalker** [comment]
Thanks for the report @JanOschii, interesting since that's the command that gets run when running `npm run webdriver-update`. Not sure how to fix ultimately for Windows here. I'll leave open for others that may know and a PR here would be appreciated if it solves for both Mac and Windows. Currently works fine on Mac.
