### ISSUE TITLE
Setup according to instructions fails at Step 5 on Windows 7 (64-Bit)

### ISSUE THREAD

**Issue by suchafreak** [NathanWalker/angular-seed-advanced#108]
How to reproduce:
Use Windows 7 
Follow Setup-Steps 1-4 to the letter
Try Step 5: `npm run merge`. 
This fails giving the following output:

```

> angular2-seed-advanced@0.0.0 merge D:\Project\angular2-seed-advanced-master
> git fetch upstream && git merge upstream/master

warning: no common commits
remote: Counting objects: 8700, done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 8700 (delta 85), reused 0 (delta 0), pack-reused 8559
Receiving objects: 100% (8700/8700), 9.56 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (4988/4988), done.
From https://github.com/NathanWalker/angular2-seed-advanced
 * [new branch]      4-electron-support -> upstream/4-electron-support
 * [new branch]      angularfire2 -> upstream/angularfire2
 * [new branch]      appveyor-fix -> upstream/appveyor-fix
 * [new branch]      master     -> upstream/master
 * [new branch]      material2  -> upstream/material2
 * [new branch]      ng2-bootstrap -> upstream/ng2-bootstrap
 * [new branch]      radsidedrawer -> upstream/radsidedrawer
 * [new branch]      sass       -> upstream/sass
 * [new branch]      ui-router  -> upstream/ui-router
error: The following untracked working tree files would be overwritten by merge:

        tools/install.js
Please move or remove them before you can merge.
Aborting

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "merge"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 merge: `git fetch upstream && git merge up
stream/master`
npm ERR! Exit status 128
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 merge script 'git fetch upst
ream && git merge upstream/master'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advance
d package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git fetch upstream && git merge upstream/master
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Project\angular2-seed-advanced-master\npm-debug.log
```

This is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'merge' ]
2 info using npm@3.8.6
3 info using node@v5.11.0
4 verbose run-script [ 'premerge', 'merge', 'postmerge' ]
5 info lifecycle angular2-seed-advanced@0.0.0~premerge: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~premerge: no script for premerge, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~merge: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~merge: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~merge: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Project\angular2-seed-advanced-master\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\PROGRA~2\Groovy\GROOVY~1.4\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files (x86)\Java\jdk1.7.0_65\bin;C:\Program Files (x86)\apache-maven-3.3.3\bin;C:\Program Files (x86)\Git\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\sascha\AppData\Roaming\npm
10 verbose lifecycle angular2-seed-advanced@0.0.0~merge: CWD: D:\Project\angular2-seed-advanced-master
11 silly lifecycle angular2-seed-advanced@0.0.0~merge: Args: [ '/d /s /c',
11 silly lifecycle   'git fetch upstream && git merge upstream/master' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~merge: Returned: code: 128  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~merge: Failed to exec merge script
14 verbose stack Error: angular2-seed-advanced@0.0.0 merge: `git fetch upstream && git merge upstream/master`
14 verbose stack Exit status 128
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd D:\Project\angular2-seed-advanced-master
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "merge"
19 error node v5.11.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 merge: `git fetch upstream && git merge upstream/master`
22 error Exit status 128
23 error Failed at the angular2-seed-advanced@0.0.0 merge script 'git fetch upstream && git merge upstream/master'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git fetch upstream && git merge upstream/master
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Regards
-sascha

**Comment by timwright35** [comment]
Fails on Linux as well on that step

**Comment by NathanWalker** [comment]
Setup instructions fixed and updated on master now.
https://github.com/NathanWalker/angular2-seed-advanced/commit/b573ab415150138691536323d322c2935916821c

Please see correct setup instructions now: https://github.com/NathanWalker/angular2-seed-advanced#setup-1
