### ISSUE TITLE
Windows production is not working

### ISSUE THREAD

**Issue by vivek-chowdhury** [NathanWalker/angular-seed-advanced#118]
Hi,

I am getting error while executing 'npm run build.desktop.windows' command. Please find the below terminal logs:

E:\Electron-Seed>npm run build.desktop.windows

> angular2-seed-advanced@0.0.0 build.desktop.windows E:\Electron-Seed
> rimraf desktop/windows/\* && gulp desktop.windows

[15:20:04] Requiring external module ts-node/register
(node:18008) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[15:20:23] Loading tasks folder E:\Electron-Seed\tools\tasks\seed
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.assets.dev
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.assets.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.bundles.app
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.bundles
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.docs
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.html_css
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.index.dev
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.index.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.dev
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.e2e
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.test
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.tools
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\check.versions
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\clean.all
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\clean.dev
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\clean.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\clean.tools
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\copy.js.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\css-lint
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\e2e
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\generate.manifest
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\karma.start
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\serve.coverage
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\serve.docs
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\server.prod
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\server.start
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\tslint
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\watch.desktop
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\watch.dev
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\watch.e2e
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\watch.test
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\seed\webdriver
[15:20:23] Loading tasks folder E:\Electron-Seed\tools\tasks\project
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\project\desktop.build
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\project\desktop.libs
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.linux
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.mac
[15:20:23] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.windows
[15:20:23] Using gulpfile E:\Electron-Seed\gulpfile.ts
[15:20:23] Starting 'desktop.windows'...
[15:20:23] Starting 'desktop'...
[15:20:23] Starting 'build.dev'...
[15:20:23] Starting 'build.assets.dev'...
[15:20:24] Finished 'build.assets.dev' after 867 ms
[15:20:24] Starting 'build.html_css'...
[15:20:25] Finished 'build.html_css' after 1.69 s
[15:20:25] Starting 'build.js.dev'...
[15:20:29] Finished 'build.js.dev' after 3.48 s
[15:20:29] Starting 'build.index.dev'...
[15:20:30] gulp-inject 6 files into index.html.
[15:20:30] gulp-inject 2 files into index.html.
[15:20:30] gulp-inject 1 files into index.html.
[15:20:30] Finished 'build.index.dev' after 922 ms
[15:20:30] Finished 'build.dev' after 6.97 s
[15:20:30] Starting 'desktop.libs'...
[15:20:40] Finished 'desktop.libs' after 10 s
[15:20:40] Starting 'desktop.build'...
[15:20:41] Finished 'desktop.build' after 868 ms
[15:20:41] Finished 'desktop' after 18 s
[15:20:41] Starting 'desktop.package.windows'...
(node:18008) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Fatal error: Unable to load file

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build.desktop.windows"
npm ERR! node v6.2.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 build.desktop.windows: `rimraf desktop/windows/* && gulp desktop.windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 build.desktop.windows script 'rimraf desktop/windows/\* && gulp desktop.windows'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf desktop/windows/\* && gulp desktop.windows
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Electron-Seed\npm-debug.log

_Request you to please guide me on this_

**Comment by NathanWalker** [comment]
I just pushed up several fixes, one of which may fix this for you. Turned out path was wrong to icon file for electron package release. Pull latest and if it fixes for you, please close this issue.

**Comment by vivek-chowdhury** [comment]
Thank you Nathan it is working now.

**Comment by vivek-chowdhury** [comment]
Hi Nathan,

Sorry to disturb you once again but it is strange that I am getting below mentioned error while executing 'npm run build.desktop.windows'. I have downloaded updated zip and tried to run build command. It works for the first time but after subsequent attempt I am getting same error. 

Request you to please guide me on this.

E:\Electron-Seed>npm run build.desktop.windows

> angular2-seed-advanced@0.0.0 build.desktop.windows E:\Electron-Seed
> rimraf desktop/windows/\* && gulp desktop.windows

[13:40:16] Requiring external module ts-node/register
(node:1088) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[13:40:33] Loading tasks folder E:\Electron-Seed\tools\tasks\seed
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.assets.dev
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.assets.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.bundles.app
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.bundles
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.docs
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.html_css
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.index.dev
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.index.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.dev
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.e2e
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.test
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\build.js.tools
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\check.versions
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\clean.all
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\clean.dev
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\clean.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\clean.tools
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\copy.js.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\css-lint
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\e2e
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\generate.manifest
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\karma.start
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\serve.coverage
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\serve.docs
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\server.prod
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\server.start
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\tslint
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\watch.dev
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\watch.e2e
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\watch.test
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\seed\webdriver
[13:40:33] Loading tasks folder E:\Electron-Seed\tools\tasks\project
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.build
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.libs
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.linux
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.mac
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.package.windows
[13:40:33] Registering task E:\Electron-Seed\tools\tasks\project\desktop.watch
[13:40:33] Using gulpfile E:\Electron-Seed\gulpfile.ts
[13:40:33] Starting 'desktop.windows'...
[13:40:33] Starting 'desktop'...
[13:40:33] Starting 'build.dev'...
[13:40:33] Starting 'build.assets.dev'...
[13:40:34] Finished 'build.assets.dev' after 777 ms
[13:40:34] Starting 'build.html_css'...
[13:40:35] Finished 'build.html_css' after 1.46 s
[13:40:35] Starting 'build.js.dev'...
[13:40:38] Finished 'build.js.dev' after 3 s
[13:40:38] Starting 'build.index.dev'...
[13:40:39] gulp-inject 6 files into index.html.
[13:40:39] gulp-inject 2 files into index.html.
[13:40:39] gulp-inject 1 files into index.html.
[13:40:39] Finished 'build.index.dev' after 1.06 s
[13:40:39] Finished 'build.dev' after 6.31 s
[13:40:39] Starting 'desktop.libs'...
[13:40:46] Finished 'desktop.libs' after 6.87 s
[13:40:46] Starting 'desktop.build'...
[13:40:47] Finished 'desktop.build' after 678 ms
[13:40:47] Finished 'desktop' after 14 s
[13:40:47] Starting 'desktop.package.windows'...
(node:1088) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Fatal error: Unable to load file

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build.desktop.windows"
npm ERR! node v6.2.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 build.desktop.windows: `rimraf desktop/windows/* && gulp desktop.windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 build.desktop.windows script 'rimraf desktop/windows/\* && gulp desktop.windows'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf desktop/windows/\* && gulp desktop.windows
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Electron-Seed\npm-debug.log

E:\Electron-Seed>

**Comment by vivek-chowdhury** [comment]
Please find the log recorded during build packaging

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build.desktop.windows' ]
2 info using npm@3.8.5
3 info using node@v6.2.1
4 verbose run-script [ 'prebuild.desktop.windows',
4 verbose run-script   'build.desktop.windows',
4 verbose run-script   'postbuild.desktop.windows' ]
5 info lifecycle angular2-seed-advanced@0.0.0~prebuild.desktop.windows: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~prebuild.desktop.windows: no script for prebuild.desktop.windows, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: PATH: C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Electron-Seed\node_modules.bin;C:\Program Files\nodejs;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\GtkSharp\2.12\bin;E:\Android\android-sdk\tools;E:\Android\android-sdk\platform-tools;C:\Android;C:\Windows\System32;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\vivek2225\AppData\Roaming\npm
10 verbose lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: CWD: E:\Electron-Seed
11 silly lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: Args: [ '/d /s /c',
11 silly lifecycle   'rimraf desktop/windows/\* && gulp desktop.windows' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: Returned: code: 1  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~build.desktop.windows: Failed to exec build.desktop.windows script
14 verbose stack Error: angular2-seed-advanced@0.0.0 build.desktop.windows: `rimraf desktop/windows/* && gulp desktop.windows`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd E:\Electron-Seed
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\vivek2225\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build.desktop.windows"
19 error node v6.2.1
20 error npm  v3.8.5
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 build.desktop.windows: `rimraf desktop/windows/* && gulp desktop.windows`
22 error Exit status 1
23 error Failed at the angular2-seed-advanced@0.0.0 build.desktop.windows script 'rimraf desktop/windows/\* && gulp desktop.windows'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rimraf desktop/windows/\* && gulp desktop.windows
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by NathanWalker** [comment]
@vivek-chowdhury is this still relevant?

**Comment by joshwiens** [comment]
@NathanWalker - This is a file semantics issue between *nix / Windows, ran into something like it in the parent a few months ago.

`rimraf desktop/windows/* && gulp desktop.windows` - rimraf tanks on glob patterns. I'll go dig up how I fixed in upstream. Testing it will take a minute, need to pull down a windows ISO to test it.

Tomorrow, late assuming all goes well with both Material2 tasks.

**Comment by NathanWalker** [comment]
This appears to be fixed. @vivek-chowdhury if you see differently, please reopen.
