### ISSUE TITLE
Electron: On linux ELIFECYCLE error while running npm run build.desktop.linux

### ISSUE THREAD

**Issue by ykoehler** [NathanWalker/angular-seed-advanced#162]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

just run npm run build.desktop.linux using npm 3.10.3 and node 6.3.0

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/home/ykoehler/angular2-seed-advanced-master/node_modules/github-releases/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket](/home/ykoehler/angular2-seed-advanced-master/node_modules/github-releases/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/home/ykoehler/angular2-seed-advanced-master/node_modules/github-releases/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:158:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/home/ykoehler/angular2-seed-advanced-master/node_modules/github-releases/node_modules/request/request.js:584:30)
    at Request.end (/home/ykoehler/angular2-seed-advanced-master/node_modules/github-releases/node_modules/request/request.js:1212:28)

npm ERR! Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build.desktop.linux"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 build.desktop.linux: `rimraf desktop/linux/* && gulp desktop.linux`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@0.0.0 build.desktop.linux script 'rimraf desktop/linux/\* && gulp desktop.linux'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf desktop/linux/\* && gulp desktop.linux
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ykoehler/angular2-seed-advanced-master/npm-debug.log

**Comment by ykoehler** [comment]
[npm-debug.zip](https://github.com/NathanWalker/angular2-seed-advanced/files/354614/npm-debug.zip)

**Comment by adrianadamski** [comment]
Try to `npm run postinstall`. This task haven't worked automatically with npm install for me on linux.

**Comment by NathanWalker** [comment]
@ykoehler did running `npm run postinstall` work for you here?

**Comment by NathanWalker** [comment]
closing due to no response.
