### ISSUE TITLE
[Nativescript] errors when running 'npm run start.livesync.android.device'

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#164]
```
Executing before-livesync hook from /home/mod/code/projects/nc/code/nc-client/nativescript/hooks/before-livesync/nativescript-angular-sync .js
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application com.yourdomain.appname on device 118e64ce.
Executing before-watch hook from /home/mod/code/projects/nc/code/nc-client/nativescript/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/app/components/home/home.component.spec.ts(31,55): error TS2304: Cannot find name 'jasmine'.

app/app/frameworks/analytics/services/analytics.service.ts(5,20): error TS2307: Cannot find module 'lodash'.

app/app/frameworks/app/services/name-list.service.spec.ts(34,26): error TS2304: Cannot find name 'jasmine'.

app/app/frameworks/core/directives/platform.directive.spec.ts(34,7): error TS2304: Cannot find name 'expect'.
app/app/frameworks/core/services/core-config.service.spec.ts(3,20): error TS2307: Cannot find module 'lodash'.
app/app/frameworks/i18n/services/multilingual.service.ts(5,20): error TS2307: Cannot find module 'lodash'.

app/app/frameworks/test/shorthand/ng2-jasmine.ts(32,19): error TS2503: Cannot find namespace 'jasmine'.
app/app/frameworks/test/shorthand/ng2-jasmine.ts(33,24): error TS2503: Cannot find namespace 'jasmine'.

app/app/frameworks/test/shorthand/ng2-jasmine.ts(41,39): error TS2503: Cannot find namespace 'jasmine'.
app/app/frameworks/test/shorthand/ng2-jasmine.ts(58,6): error TS2304: Cannot find name 'expect'.
app/app/frameworks/test/shorthand/ng2-jasmine.ts(59,11): error TS2304: Cannot find name 'expect'.
app/app/frameworks/test/shorthand/ng2-jasmine.ts(66,12): error TS2304: Cannot find name 'pending'.

app/app/frameworks/test/shorthand/ng2-jasmine.ts(67,10): error TS2304: Cannot find name 'spyOn'.

2:48:22 PM - Compilation complete. Watching for file changes.

W/System.err(21713): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err(21713): Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err(21713):    at com.tns.Runtime.createJSInstanceNative(Native Method)
W/System.err(21713):    at com.tns.Runtime.createJSInstance(Runtime.java:367)
```

why is there a space in:

```
Executing before-livesync hook from /home/mod/code/projects/nc/code/nc-client/nativescript/hooks/before-livesync/nativescript-angular-sync .js
```

**Comment by divramod** [comment]
i was able to remove the errors after uninstalling the app via adb
