### ISSUE TITLE
NativeScript wont run after installation

### ISSUE THREAD

**Issue by archonik** [NathanWalker/angular-seed-advanced#177]
**Steps to reproduce and a minimal demo of the problem**
Just Downloaded the repo and run 

npm install
npm run start.android

**Current behavior**
`EXCEPTION: Error in /data/data/com.yourdomain.appname/files/app/app/components/app/app.component.tns.html:2:2
ORIGINAL EXCEPTION: TypeError: Cannot read property 'take' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'take' of undefined
    at SafeSubscriber._next (/data/data/com.yourdomain.appname/files/app/app/frameworks/i18n/services/multilingual.service.js:59:55)
    at SafeSubscriber.__tryOrUnsub (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:225:16)
    at SafeSubscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:174:22)
    at Subscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:124:26)
    at Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
    at DistinctUntilChangedSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/distinctUntilChanged.js:72:30)
    at DistinctUntilChangedSubscriber.Subscri`

**Expected/desired behavior**
To be able to run nativescript app

**Other information**
`
$ node --version
v6.3.0

$ npm --version
3.10.3

$ tns --version
2.1.1

Windows:
10-pro
build 1511
`

**Comment by NathanWalker** [comment]
sounds like you may have downloaded before the fix went up for that... please try downloading again, that fix went in on 22nd: https://github.com/NathanWalker/angular2-seed-advanced/commit/f4b4e5d09249151a9c3f6bce1470c371a217e905  Please close once you have done so.

**Comment by archonik** [comment]
Ok Works
