### ISSUE TITLE
Fails on Setup Step 5 (OSX 10.9.5 w/ Node 4.4.7 & 6.3.1)

### ISSUE THREAD

**Issue by danielnola** [NathanWalker/angular-seed-advanced#199]
OSX 10.9.5
Setup steps 1-4 work fine
I've tried using both Node LTS v4.4.7 (includes npm 2.15.8) and Current v6.3.1 (includes npm 3.10.3).
Fails on Step 5 w/ the following in terminal:

```
DONT_MATTER$ npm run git.merge

> angular2-seed-advanced@0.0.0 git.merge /Users/DD/prog/angular2-seed-advanced
> git fetch upstream && git merge upstream/master

warning: no common commits
remote: Counting objects: 10220, done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 10220 (delta 41), reused 0 (delta 0), pack-reused 10109
Receiving objects: 100% (10220/10220), 10.26 MiB | 3.31 MiB/s, done.
Resolving deltas: 100% (5818/5818), done.
From https://github.com/NathanWalker/angular2-seed-advanced
 * [new branch]      4-electron-support -> upstream/4-electron-support
 * [new branch]      angularfire2 -> upstream/angularfire2
 * [new branch]      appveyor-fix -> upstream/appveyor-fix
 * [new branch]      master     -> upstream/master
 * [new branch]      material2  -> upstream/material2
 * [new branch]      nativescript-dropdown-and-font-icons -> upstream/nativescript-dropdown-and-font-icons
 * [new branch]      ng2-bootstrap -> upstream/ng2-bootstrap
 * [new branch]      pdf-reports -> upstream/pdf-reports
 * [new branch]      radsidedrawer -> upstream/radsidedrawer
 * [new branch]      sass       -> upstream/sass
 * [new branch]      ui-router  -> upstream/ui-router
Auto-merging typings.json
CONFLICT (add/add): Merge conflict in typings.json
Auto-merging tslint.json
CONFLICT (add/add): Merge conflict in tslint.json
Auto-merging tsconfig.json

**[EDITED FOR BREVITY]**

Auto-merging .github/CONTRIBUTING.md
CONFLICT (add/add): Merge conflict in .github/CONTRIBUTING.md
Auto-merging .editorconfig
CONFLICT (add/add): Merge conflict in .editorconfig
Automatic merge failed; fix conflicts and then commit the result.

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/nvm/versions/node/v6.3.1/bin/node" "/usr/local/nvm/versions/node/v6.3.1/bin/npm" "run" "git.merge"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@0.0.0 git.merge script 'git fetch upstream && git merge upstream/master'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git fetch upstream && git merge upstream/master
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DD/prog/angular2-seed-advanced/npm-debug.log
```

Log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/versions/node/v6.3.1/bin/node',
1 verbose cli   '/usr/local/nvm/versions/node/v6.3.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'git.merge' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'pregit.merge', 'git.merge', 'postgit.merge' ]
5 info lifecycle angular2-seed-advanced@0.0.0~pregit.merge: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~pregit.merge: no script for pregit.merge, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~git.merge: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: PATH: /usr/local/nvm/versions/node/v6.3.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/DD/prog/angular2-seed-advanced/node_modules/.bin:/usr/local/nvm/versions/node/v6.3.1/bin:/usr/local/nvm/versions/node/v6.3.1/bin:/Users/DD/.rvm/gems/ruby-2.2.2/bin:/Users/DD/.rvm/gems/ruby-2.2.2@global/bin:/Users/DD/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/DD/.rvm/bin
10 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: CWD: /Users/DD/prog/angular2-seed-advanced
11 silly lifecycle angular2-seed-advanced@0.0.0~git.merge: Args: [ '-c', 'git fetch upstream && git merge upstream/master' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~git.merge: Returned: code: 1  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~git.merge: Failed to exec git.merge script
14 verbose stack Error: angular2-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/nvm/versions/node/v6.3.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd /Users/DD/prog/angular2-seed-advanced
17 error Darwin 13.4.0
18 error argv "/usr/local/nvm/versions/node/v6.3.1/bin/node" "/usr/local/nvm/versions/node/v6.3.1/bin/npm" "run" "git.merge"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master`
22 error Exit status 1
23 error Failed at the angular2-seed-advanced@0.0.0 git.merge script 'git fetch upstream && git merge upstream/master'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git fetch upstream && git merge upstream/master
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joshwiens** [comment]
Git merge is going to fail as conflicts are a failure condition for that process.

**Comment by NathanWalker** [comment]
@d3viant0ne is correct. In the README, such is stated here:
https://github.com/NathanWalker/angular2-seed-advanced#setup-1 within the _IMPORTANT_ note following step 5. This is normal.
