### ISSUE TITLE
npm install fails on OS X

### ISSUE THREAD

**Issue by klall** [NathanWalker/angular-seed-advanced#219]
I followed the instructions for the installation correctly I believe as the logs below show. I even tried to update the version of gulp in package.json but then had further issues. You can see the version of node and gulp I am using below as well. Have I installed something wrong? I used these instructions: https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4 and even these https://demisx.github.io/gulp4/2015/01/15/install-gulp4.html

09:32 $ git clone --depth 1 https://github.com/NathanWalker/angular2-seed-advanced.git
Cloning into 'angular2-seed-advanced'...
remote: Counting objects: 353, done.
remote: Compressing objects: 100% (320/320), done.
remote: Total 353 (delta 19), reused 194 (delta 13), pack-reused 0
Receiving objects: 100% (353/353), 1.78 MiB | 381.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
Checking connectivity... done.

✔ ~/Box Sync/explore [master L|…30726] 
09:32 $ node --version
v6.4.0

✔ ~/Box Sync/explore [master L|…30726] 
09:32 $ gulp --version
[09:32:47] CLI version 1.2.2
[09:32:47] Local version 4.0.0-alpha.2

✔ ~/Box Sync/explore [master L|…30726] 
09:32 $ cd angular2-seed-advanced/
✔ ~/Box Sync/explore/angular2-seed-advanced [master|✔] 
09:32 $ npm i
npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:39469) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> fsevents@1.0.14 install /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> node-sass@3.9.0 install /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.0/darwin-x64-48_binding.node
Binary downloaded and installed at /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/node-sass/vendor/darwin-x64-48/binding.node

> node-sass@3.9.0 postinstall /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/node-sass
> node scripts/build.js

"/Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/node-sass/vendor/darwin-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> electron-prebuilt@1.3.5 postinstall /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/electron-prebuilt
> node install.js
> 
> angular2-seed-advanced@0.0.0 postinstall /Users/kamlall/Box Sync/explore/angular2-seed-advanced
> typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js

├── xhr2
├── Q (global)
├── angular-protractor (global)
├── async (global)
├── browser-sync (global)
├── chalk (global)
├── chokidar (global)
├── core-js (global)
├── express (global)
├── glob (global)
├── gulp (global)
├── gulp-load-plugins (global)
├── gulp-protractor (global)
├── gulp-sass (global)
├── gulp-shell (global)
├── gulp-util (global)
├── jasmine (global)
├── lodash (global)
├── micromatch (global)
├── mime (global)
├── minimatch (global)
├── ng2 (global)
├── node (global)
├── orchestrator (global)
├── parse-glob (global)
├── rimraf (global)
├── run-sequence (global)
├── selenium-webdriver (global)
├── serve-static (global)
├── systemjs (global)
├── through2 (global)
├── vinyl (global)
├── vinyl-source-stream (global)
├── yargs (global)
└── zone.js (global)

[09:36:48] Working directory changed to ~/Box Sync/explore
[09:36:48] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/browsersync.js
[09:36:48] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/build.js
[09:36:49] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/karma.js
[09:36:50] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/misc.js
[09:36:50] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/scripts.js
[09:36:50] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/styles.js
[09:36:50] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/systemjs.js
[09:36:50] Using gulpfile ~/Box Sync/explore/gulpfile.js
/Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/kamlall/Box Sync/explore/angular2-seed-advanced/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by klall** [comment]
Never mind, not sure why I upgraded to gulp 4 as that isn't a requirement. Closing issue.
