### ISSUE TITLE
Problem with 'npm run git.merge' on git >= 2.9

### ISSUE THREAD

**Issue by robbatt** [NathanWalker/angular-seed-advanced#223]
**Steps to reproduce and a minimal demo of the problem**
1. update your machine's git version to >= 2.9
2. download project zip
3. follow setup in Readme "Usage for my project"
4. at step 'npm run git.merge' you will see a 'fatal: refusing to merge unrelated histories'

**Current behavior**

merge is refused

**Expected/desired behavior**

merge is successful

**Other information**

I was able to resolve this by adding '--allow-unrelated-histories' to git merge manually, see http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories

Adding this to the npm script would break it for versions < 2.9 (unknown option --allow-unreleated-histories) 
so either we add a check for git version (ugly in package.json) 
or provide a second script (ugly for user).

**Comment by NathanWalker** [comment]
Thanks for bringing this up @robbatt ... I'll leave this issue open for some time for others who may come across the problem. Thanks for documenting!

**Comment by NTPLThavarajan** [comment]
i am having this error

this is my npm-log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'git.merge' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'pregit.merge', 'git.merge', 'postgit.merge' ]
5 info lifecycle angular2-seed-advanced@0.0.0~pregit.merge: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~pregit.merge: no script for pregit.merge, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~git.merge: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: PATH: C:\Users\xxxxx\AppData\Roaming\nvm\v6.3.1\node_modules\npm\bin\node-gyp-bin;D:\angular2-seed-advanced\angular2-advanced\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Kaspersky Lab\Kaspersky Endpoint Security 10 for Windows\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Users\xxxxx\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\MongoDB\Server\3.2\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Users\xxxxx\AppData\Local\Android\android-sdk\tools;C:\Users\xxxxx\AppData\Local\Android\android-sdk\platform-tools;C:\Users\xxxxx\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\xxxxx\AppData\Roaming\npm\
10 verbose lifecycle angular2-seed-advanced@0.0.0~git.merge: CWD: D:\angular2-seed-advanced\angular2-advanced
11 silly lifecycle angular2-seed-advanced@0.0.0~git.merge: Args: [ '/d /s /c',
11 silly lifecycle   'git fetch upstream && git merge upstream/master' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~git.merge: Returned: code: 128  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~git.merge: Failed to exec git.merge script
14 verbose stack Error: angular2-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master`
14 verbose stack Exit status 128
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxxxx\AppData\Roaming\nvm\v6.3.1\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxxxx\AppData\Roaming\nvm\v6.3.1\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd D:\angular2-seed-advanced\angular2-advanced
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "git.merge"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master`
22 error Exit status 128
23 error Failed at the angular2-seed-advanced@0.0.0 git.merge script 'git fetch upstream && git merge upstream/master'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git fetch upstream && git merge upstream/master
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by govi2010** [comment]
I am getting error when i run `npm run git.merge`

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'git.merge' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'pregit.merge', 'git.merge', 'postgit.merge' ]
5 info lifecycle angular-seed-advanced@0.0.0~pregit.merge: angular-seed-advanced@0.0.0
6 silly lifecycle angular-seed-advanced@0.0.0~pregit.merge: no script for pregit.merge, continuing
7 info lifecycle angular-seed-advanced@0.0.0~git.merge: angular-seed-advanced@0.0.0
8 verbose lifecycle angular-seed-advanced@0.0.0~git.merge: unsafe-perm in lifecycle true
9 verbose lifecycle angular-seed-advanced@0.0.0~git.merge: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/macbookpro/Work/OBEKTech/obek/angular-seed-advanced-master/node_modules/.bin:/Users/macbookpro/Library/Android/sdk/tools:/Users/macbookpro/Library/Android/sdk/platform-tools:/Users/macbookpro/Library/Android/sdk/build-toold:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet
10 verbose lifecycle angular-seed-advanced@0.0.0~git.merge: CWD: /Users/macbookpro/Work/OBEKTech/obek/angular-seed-advanced-master
11 silly lifecycle angular-seed-advanced@0.0.0~git.merge: Args: [ '-c',
11 silly lifecycle   'git fetch upstream && git merge upstream/master --allow-unrelated-histories' ]
12 silly lifecycle angular-seed-advanced@0.0.0~git.merge: Returned: code: 1  signal: null
13 info lifecycle angular-seed-advanced@0.0.0~git.merge: Failed to exec git.merge script
14 verbose stack Error: angular-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master --allow-unrelated-histories`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-seed-advanced@0.0.0
16 verbose cwd /Users/macbookpro/Work/OBEKTech/obek/angular-seed-advanced-master
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "git.merge"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master --allow-unrelated-histories`
22 error Exit status 1
23 error Failed at the angular-seed-advanced@0.0.0 git.merge script 'git fetch upstream && git merge upstream/master --allow-unrelated-histories'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git fetch upstream && git merge upstream/master --allow-unrelated-histories
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

`git version 2.10.2`

**Comment by govi2010** [comment]
Ok just read that this is normal

**Comment by coquizen** [comment]
Running Mac OS Sierra
npm = 4.0.5
node = 6.7.0
git = 2.11.0

Following the directions as stated in the wiki for a clean download of this I get the following:
```
angular-seed-advanced@0.0.0 git.merge: `git fetch upstream && git merge upstream/master --allow-unrelated-histories`
npm ERR! Exit status 1
```
When attempting to run manually I get the same errors as above.

Investigation reveals that somehow package.json got peppered with git headers:

```
{
  "name": "angular-seed-advanced",
  "version": "0.0.0",
  "description": "High-quality, modular starter (advanced seed) project for Angular 2 apps with statically typed build and AoT + NativeScript + Electron",
  "repository": {
    "url": "https://github.com/NathanWalker/angular-seed-advanced"
  },
  "scripts": {
    "build.desktop.mac": "rimraf desktop/mac/* && gulp desktop.mac",
    "build.desktop.windows": "rimraf desktop/windows/* && gulp desktop.windows",
    "build.desktop.linux": "rimraf desktop/linux/* && gulp desktop.linux",
<<<<<<< HEAD
    "build.dev": "gulp build.dev --color --config-env dev",
    "build.dev.watch": "gulp build.dev.watch --color",
    "build.docs": "npm run gulp -- build.docs --color",
    "build.e2e": "gulp build.e2e --color",
    "build.prod": "gulp build.prod --color --config-env prod",
    "build.prod.exp": "gulp build.prod.exp --color --config-env prod",
=======
    "build.dev": "gulp build.dev --color --env-config dev",
    "build.dev.watch": "gulp build.dev.watch --color",
    "build.docs": "npm run gulp -- build.docs --color",
    "build.e2e": "gulp build.e2e --color",
    "build.prod": "gulp build.prod --color --env-config prod --build-type prod",
    "build.prod.exp": "gulp build.prod.exp --color --env-config prod --build-type prod",
>>>>>>> upstream/master
    "build.test": "gulp build.test --color",
    "clean": "npm run clean.js && rm -rf node_modules typings && cd nativescript && rm -rf node_modules hooks lib platforms && cd .. && npm i",
    "clean.js": "gulp clean.all.src.js",
    "test.watch": "gulp test.watch --color",
    "generate.manifest": "gulp generate.manifest --color",
    "e2e": "protractor",
    "e2e.live": "protractor --elementExplorer",
    "git.merge": "git fetch upstream && git merge upstream/master --allow-unrelated-histories",
    "git.merge.legacy": "git fetch upstream && git merge upstream/master",
    "git.merge.preview": "git fetch upstream && git merge --no-commit upstream/master",
    "git.merge.preview.legacy": "git fetch upstream && git merge --no-commit upstream/master --allow-unrelated-histories",
    "git.prepare": "git add . && git add -f tools/install.js && git commit -m'setup'",
    "git.setup": "git init && git remote add upstream https://github.com/NathanWalker/angular-seed-advanced.git",
    "gulp": "gulp",
    "i18n": "ng-xi18n && gulp clean.i18n",
    "lint": "gulp tslint",
    "karma": "karma",
    "karma.start": "karma start",
    "postinstall": "gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && node tools/install.js",
    "reinstall": "npm cache clean && npm install",
<<<<<<< HEAD
    "serve.coverage": "remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color",
    "serve.dev": "gulp serve.dev --color --config-env dev",
    "serve.docs": "npm run gulp -- build.docs --color && npm run gulp -- serve.docs --color",
    "serve.e2e": "gulp serve.e2e --color",
    "serve.prod": "gulp serve.prod --color --config-env prod",
=======
    "serve.coverage": "gulp serve.coverage --color",
    "serve.dev": "gulp serve.dev --color --env-config dev",
    "serve.e2e": "gulp serve.e2e --color",
    "serve.prod": "gulp serve.prod --color --env-config prod",
    "serve.prod.exp": "gulp serve.prod.exp --color --env-config prod",
>>>>>>> upstream/master
    "start": "gulp serve.dev --color",
    "start.deving": "gulp start.deving --color",
    "start.desktop": "gulp desktop && NODE_ENV=development electron ./dist/dev",
    "start.livesync.desktop": "gulp desktop && NODE_ENV=development gulp desktop.watch",
    "start.livesync.desktop.windows": "gulp desktop && SET NODE_ENV=development && gulp desktop.watch",
    "start.desktop.windows": "gulp desktop && SET NODE_ENV=development && electron ./dist/dev",
    "start.ios": "cd nativescript && npm i && tns emulate ios --disableNpmInstall",
    "start.livesync.ios": "cd nativescript && tns livesync ios --emulator --watch --disableNpmInstall",
    "start.livesync.ios.device": "cd nativescript && tns livesync ios --watch --disableNpmInstall",
    "start.android": "cd nativescript && npm i && tns emulate android --disableNpmInstall",
    "start.livesync.android": "cd nativescript && tns livesync android --emulator --watch --disableNpmInstall",
    "start.livesync.android.device": "cd nativescript && tns livesync android --watch --disableNpmInstall",
    "tasks.list": "gulp --tasks-simple --color",
    "test": "gulp test --color",
    "e2e.ci": "gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color",
    "tests.all": "npm test && npm run e2e.ci",
<<<<<<< HEAD
    "webdriver-start": "node_modules/protractor/bin/webdriver-manager start",
    "webdriver-update": "node_modules/protractor/bin/webdriver-manager update"
=======
    "webdriver-start": "webdriver-manager start",
    "webdriver-update": "webdriver-manager update",
    "compodoc": "node_modules/.bin/compodoc -p src/client/tsconfig.json",
    "serve.compodoc": "node_modules/.bin/compodoc -s"
>>>>>>> upstream/master
  },
  "author": "Minko Gechev <mgechev>",
  "contributors": [
    {
      "name": "Nathan Walker <NathanWalker>"
    }
  ],
  "license": "MIT",
  "devDependencies": {
<<<<<<< HEAD
    "@angular/compiler-cli": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@angular/tsc-wrapped": "^0.3.0",
    "@types/async": "^2.0.32",
    "@types/browser-sync": "^0.0.34",
    "@types/core-js": "^0.9.34",
    "@types/express": "^4.0.33",
    "@types/gulp": "^3.8.32",
=======
    "@angular/compiler-cli": "~2.4.0",
    "@angular/platform-server": "~2.4.0",
    "@ngrx/store-devtools": "^3.2.2",
    "@types/async": "^2.0.32",
    "@types/browser-sync": "^0.0.34",
    "@types/express": "^4.0.33",
    "@types/gulp": "^3.8.32",
    "@types/gulp-filter": "^3.0.29",
>>>>>>> upstream/master
    "@types/gulp-load-plugins": "^0.0.28",
    "@types/gulp-protractor": "^1.0.29",
    "@types/gulp-sass": "^0.0.29",
    "@types/gulp-util": "^3.0.29",
    "@types/jasmine": "^2.5.35",
    "@types/lodash": "^4.14.37",
    "@types/node": "^6.0.45",
    "@types/protractor": "^1.5.20",
    "@types/rimraf": "0.0.28",
    "@types/run-sequence": "^0.0.28",
    "@types/selenium-webdriver": "2.44.*",
    "@types/systemjs": "^0.19.31",
<<<<<<< HEAD
    "@types/yargs": "^0.0.33",
=======
    "@types/yargs": "^0.0.34",
>>>>>>> upstream/master
    "@types/zone.js": "^0.0.27",
    "async": "^2.1.1",
    "autoprefixer": "^6.5.1",
    "browser-sync": "^2.17.3",
<<<<<<< HEAD
    "codelyzer": "~1.0.0-beta.2",
=======
    "codelyzer": "~2.0.0-beta.3",
    "compodoc": "^0.0.18",
>>>>>>> upstream/master
    "connect-history-api-fallback": "^1.3.0",
    "cssnano": "^3.7.7",
    "deep-extend": "^0.4.1",
    "electron-connect": "^0.4.2",
    "electron-debug": "^1.0.0",
    "electron-prebuilt": "^1.2.1",
    "event-stream": "^3.3.4",
    "express": "~4.14.0",
    "express-history-api-fallback": "^2.0.0",
    "gulp": "^3.9.1",
    "gulp-atom-electron": "^1.6.1",
    "gulp-cached": "^1.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-concat-css": "^2.3.0",
    "gulp-filter": "^4.0.0",
    "gulp-inject": "^4.1.0",
<<<<<<< HEAD
    "gulp-inline-ng2-template": "^3.0.1",
=======
    "gulp-inline-ng2-template": "^4.0.0",
>>>>>>> upstream/master
    "gulp-load-plugins": "^1.3.0",
    "gulp-newer": "^1.3.0",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "^6.2.0",
    "gulp-progeny": "^0.3.1",
    "gulp-protractor": "^3.0.0",
    "gulp-replace": "^0.5.4",
    "gulp-sass": "^2.3.2",
<<<<<<< HEAD
    "gulp-sourcemaps": "2.1.1",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "^6.1.2",
    "gulp-typedoc": "^2.0.0",
=======
    "gulp-sourcemaps": "2.2.0",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "7.0.1",
>>>>>>> upstream/master
    "gulp-typescript": "^3.0.2",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.10",
    "is-ci": "^1.0.9",
    "isstream": "^0.1.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "~1.3.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "~1.0.2",
    "karma-mocha-reporter": "^2.2.0",
    "karma-remap-istanbul": "^0.2.1",
    "merge-stream": "^1.0.0",
<<<<<<< HEAD
=======
    "minimatch": "^3.0.3",
    "ngrx-store-freeze": "0.1.0",
>>>>>>> upstream/master
    "open": "0.0.5",
    "protractor": "^4.0.9",
    "remap-istanbul": "^0.7.0",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "semver": "^5.3.0",
    "serve-static": "^1.11.1",
    "slash": "~1.0.0",
<<<<<<< HEAD
    "systemjs-builder": "0.15.32",
    "tildify": "^1.2.0",
    "traceur": "^0.0.111",
    "ts-node": "^1.4.3",
    "tslint": "^3.15.1",
    "typedoc": "^0.5.0",
    "typescript": "^2.0.3",
=======
    "supports-color": "^3.1.2",
    "systemjs-builder": "0.15.33",
    "tildify": "^1.2.0",
    "traceur": "^0.0.111",
    "ts-node": "^1.4.3",
    "tslint": "~4.0.0",
    "typedoc": "^0.5.0",
    "typescript": "~2.0.9",
>>>>>>> upstream/master
    "walk": "^2.3.9",
    "yargs": "^6.0.0"
  },
  "dependencies": {
<<<<<<< HEAD
    "@angular/common": "^2.1.1",
    "@angular/compiler": "^2.1.1",
    "@angular/core": "^2.1.1",
    "@angular/forms": "^2.1.1",
    "@angular/http": "^2.1.1",
    "@angular/platform-browser": "^2.1.1",
    "@angular/platform-browser-dynamic": "^2.1.1",
    "@angular/router": "^3.1.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "angulartics2": "^1.1.11",
    "core-js": "^2.4.1",
    "es-module-loader": "^1.0.0",
    "lodash": "^4.16.4",
    "ng2-translate": "^3.1.3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "0.6.25"
=======
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/store": "^2.2.1",
    "angulartics2": "^1.4.3",
    "core-js": "^2.4.1",
    "es-module-loader": "^1.0.0",
    "intl": "^1.2.5",
    "lodash": "^4.16.4",
    "minimatch": "^3.0.3",
    "ng2-config": "^1.1.1",
    "ng2-translate": "^5.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.2",
    "systemjs": "0.19.40",
    "zone.js": "^0.7.2"
>>>>>>> upstream/master
  }
}

```
