### ISSUE TITLE
NPM run clean fails with TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by fbascheper** [NathanWalker/angular-seed-advanced#232]
After a rebase on master, npm run clean fails with the following error:

```
10:03:47] TSError: ⨯ Unable to compile TypeScript
tools/tasks/seed/clean.all.src.js.ts (7,10): Module '"/klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/tools/config"' has no exported member 'APP_SRC'. (2305)
    at getOutput (/klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/node_modules/ts-node/src/index.ts:253:17)
    at /klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/klant/connectender/website/angular2-seed-advanced-github-fork-fbascheper/node_modules/ts-node/src/index.ts:302:14)
```

Expected behaviour: the command should execute normally.

**Comment by willSonic** [comment]
I had similar problem using electron npm run command. I was able to fix the problem by updating 
**tools/tasks/project/**
                      desktop.build.ts
                      desktop.lib.ts
**tools/task/seed/**
                  build.docs.ts
                  clean.all.src.js.ts

so that  it matches other tps import of configs in similar files.. 

changed:
import { APP_SRC, APP_TITLE, DOCS_DEST } from '../../config';

to:
import Config  from '../../config';

then in the class implementation:
Config.APP_SRC
Config.APP_TITLE
Config.DOCS_DEST

**Comment by NathanWalker** [comment]
@fbascheper @willSonic not sure how those didn't make the push last night.
Fixed on master now 👍
