### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by Jonatthu** [NathanWalker/angular-seed-advanced#329]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
With node version 6.9.1 and npm 4.0.5 in Mac
after npm install and npm start commands

[09:03:28] 'build.dev' errored after 13 s
[09:03:28] Error in plugin 'run-sequence(serve.dev)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at /Users/jonatthu/Desktop/testApp/tools/config/seed.config.ts:685:59
    at Array.forEach (native)
    at normalizeDependencies (/Users/jonatthu/Desktop/testApp/tools/config/seed.config.ts:685:6)
    at ProjectConfig.get [as DEPENDENCIES] (/Users/jonatthu/Desktop/testApp/tools/config/seed.config.ts:375:12)
    at getExternalCss (/Users/jonatthu/Desktop/testApp/tools/tasks/seed/build.html_css.ts:139:16)
    at getExternalCssStream (/Users/jonatthu/Desktop/testApp/tools/tasks/seed/build.html_css.ts:131:19)
    at processExternalCss (/Users/jonatthu/Desktop/testApp/tools/tasks/seed/build.html_css.ts:163:10)
    at processExternalStylesheets (/Users/jonatthu/Desktop/testApp/tools/tasks/seed/build.html_css.ts:112:65)

**Comment by NathanWalker** [comment]
Hi @geminiyellow I just cloned fresh master, ran npm i, then npm start and do not see this issue.
I'm running:
node 6.9.1, npm 3.10.9 and on a Mac (Sierra)

It could be your environment?

**Comment by lucasvanhalst** [comment]
It's just his postinstall script that has failed to run. try `npm run postinstall`

**Comment by geminiyellow** [comment]
🤣  @NathanWalker , you copy the comment just for me to here, i feel so sad.

**Comment by NathanWalker** [comment]
Oh no what happened @geminiyellow?

**Comment by NathanWalker** [comment]
N/a.

**Comment by xjjrain2012** [comment]
npm run-script postinstall
