### ISSUE TITLE
gulp cannot find module,

### ISSUE THREAD

**Issue by dawning321** [NathanWalker/angular-seed-advanced#400]
**I'm submitting a bug report**  (check one with "x")

**Current behavior**

$ sudo yarn install
[09:41:04] Using gulpfile ~/Downloads/angular-seed-advanced-master/gulpfile.js
[09:41:04] Starting 'check.versions'...
[09:41:04] 'check.versions' errored after 250 μs
[09:41:04] Error: Cannot find module '/Users/xxxx/Downloads/angular-seed-advanced-master/tools/tasks/seed/check.versions'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Gulp.<anonymous> (/Users/xxxx/Downloads/angular-seed-advanced-master/tools/utils/seed/tasks_tools.js:107:34)
    at module.exports (/Users/xxxx/Downloads/angular-seed-advanced-master/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/xxxx/Downloads/angular-seed-advanced-master/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/xxxx/Downloads/angular-seed-advanced-master/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/xxxx/Downloads/angular-seed-advanced-master/node_modules/orchestrator/index.js:134:8)
    at /Users/xxxx/Downloads/angular-seed-advanced-master/node_modules/gulp/bin/gulp.js:129:20
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.**Expected behavior**

$ gulp
/Users/xxxx/Downloads/angular-seed-advanced-master/tools/config/seed-advanced.config.js:27
            if (arg.indexOf('desktop') > -1) {
                   ^

TypeError: Cannot read property 'indexOf' of undefined
    at ProjectConfig.SeedAdvancedConfig [as constructor] (/Users/xxxx/Downloads/angular-seed-advanced-master/tools/config/seed-advanced.config.js:27:20)
    at new ProjectConfig (/Users/xxxx/Downloads/angular-seed-advanced-master/tools/config/project.config.js:12:28)
    at Object.<anonymous> (/Users/xxxx/Downloads/angular-seed-advanced-master/tools/config.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

mac,
gulp:CLI version 3.9.1
        Local version 3.9.1
* **Angular Seed Version:** `aaaaf75`
node: v7.8.0
npm:4.2.0

* **Node:** `node --version` = v7.8.0

**Comment by shmuelios** [comment]
I had the same problem
This solved it https://github.com/mgechev/angular-seed/issues/902#issuecomment-220836062
remove the gulpfile.js

**Comment by NathanWalker** [comment]
Thank you @shmuelios yes indeed that is the fix for this issue 👍
