### ISSUE TITLE
npm run build.prod failed on Ubuntu

### ISSUE THREAD

**Issue by vladyhon** [NathanWalker/angular-seed-advanced#409]
npm run build.prod failed. i read that i have to add some path to seed.confid.ts but don't know what exactly. I merged the latest version of upstream/master branch but maybe i lost something or deleted,
can you just say what file i should compare with your angular-seed+
```
[ ] bug report => https://github.com/mgechev/angular-seed/issues/975
```

**Current behavior**
 ENOENT: no such file or directory, open 'my-path-to-project/dist/tmp/app/components/app.component.html'
    at Error (native)                                                                                                                                                
    at Object.fs.openSync (fs.js:641:18)                                                                                                                             
    at Object.fs.readFileSync (fs.js:509:33)                                                                                                                         
    at getFileData (/home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/gulp-inline-ng2-template/parser.js:284:17)                                   
    at /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/gulp-inline-ng2-template/parser.js:248:22                                                 
    at /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/async/dist/async.js:3816:26                                                               
    at replenish (/home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/async/dist/async.js:982:17)                                                    
    at /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/async/dist/async.js:986:9                                                                 
    at eachOfLimit (/home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/async/dist/async.js:1011:22)                                                 
    at /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/async/dist/async.js:1016:16                                                               
                                                                                             

**Expected behavior**
Successful production build

**Minimal reproduction of the problem with instructions**
npm run build.prod

**Please tell us about your environment:**
Ubuntu 16.04
Visual code

* **Angular Seed Version:** `aaaaf75`
latest upstream/master changes

* **Node:** `node --version` = 6.10.2

**Comment by sean-perkins** [comment]
@vhontar If you are merging from upstream, check to see if `AppComponent` exists where the error is stating.

`app/components/app.component.html`

If it's not, either add it or remove the existing references from the module looking for it.

**Comment by vladyhon** [comment]
problem was with basecomponent, that was deleted from framework
