### ISSUE TITLE
Running the seed on heroku

### ISSUE THREAD

**Issue by blaur** [NathanWalker/angular-seed-advanced#448]
Hi guys,

I am looking for some help. It might simply be because of my lack of knowledge but hopefully you won't judge ;)

I've been trying to push the seed to heroku (to verify the difficulty in doing so) since I will be running the staging system there. 

When pushing I am seeing the following error and I am pretty much stuck at the moment:
```
remote:        $ gulp build.dev --color --env-config dev
remote:        [16:29:10] Failed to load external module ts-node/register
remote:        [16:29:10] Failed to load external module typescript-node/register
remote:        [16:29:10] Failed to load external module typescript-register
remote:        [16:29:10] Failed to load external module typescript-require
remote:        /tmp/build_f9f58f3c0733f36bf19ec5e5278434ed/gulpfile.ts:1
remote:        (function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
remote:        ^^^^^^
remote:        SyntaxError: Unexpected token import
remote:        at createScript (vm.js:56:10)
remote:        at Object.runInThisContext (vm.js:97:10)
remote:        at Module._compile (module.js:542:28)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Liftoff.handleArguments (/tmp/build_f9f58f3c0733f36bf19ec5e5278434ed/node_modules/gulp/bin/gulp.js:116
```

Anyone who can help?

**Comment by megetron** [comment]
@blaur did you make the seed works with heroku?
