### ISSUE TITLE
Unable to run on iOS emulator using `npm run start.ios`

### ISSUE THREAD

**Issue by avhetman** [NathanWalker/angular-seed-advanced#492]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
Running `npm run start.ios` results in an error:

[1] 1   0x10c22d25c -[TNSRuntime executeModule:referredBy:]
[1] 2   0x10bc99d4e main
[1] 3   0x10f72d575 start
[1] 4   0x1
[1] [native code]: JS ERROR Error: Could not find module './'. Computed path '/Users/ahetma437/Library/Developer/CoreSimulator/Devices/F1D2C039-472E-4678-B8F9-A9813FA631BE/data/Containers/Bundle/Application/6DC9CC37-6077-4481-8172-316040D39C72/nativescript.app/app'.

**Expected behavior**
Expected emulator to work and display the app.

**Minimal reproduction of the problem with instructions**
clone latest seed, npm i, npm run start.ios

**What is the motivation / use case for changing the behavior?**
Evaluating using the seed

**Please tell us about your environment:**
iOS macbook mojave

* **Angular Seed Version:** `aaaaf75`
Latest as of Nov 19 2018

* **Node:** `node --version` =
Node -v 10.13.0
npm -v 6.4.1

**Comment by avhetman** [comment]
Running `npm run start.android` also fails with this terminal error message:

System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
[1] System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
[1] System.err: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
[1] System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
[1] System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[1] System.err: 	at android.os.Looper.loop(Looper.java:154)
[1] System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[1] System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[1] System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[1] System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[1] System.err: Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
[1] System.err: 	at com.tns.Module.bootstrapApp(Module.java:311)
[1] System.err: 	at com.tns.Runtime.run(Runtime.java:512)
[1] System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
[1] System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
[1] System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
[1] System.err: 	... 8 more
[1] System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
[1] System.err: 	at com.tns.Module.resolvePathHelper(Module.java:146)
[1] System.err: 	at com.tns.Module.bootstrapApp(Module.java:309)
[1] System.err: 	... 12 more
[1] Successfully transferred app.gradle on device emulator-5554.
[1] Refreshing application on device emulator-5554...
[1] Successfully synced application com.yourdomain.nativescript on device emulator-5554.
