### ISSUE TITLE
Error while running protractor tests

### ISSUE THREAD

**Issue by JakePartusch** [NathanWalker/angular-seed-advanced#67]
**Steps to reproduce and a minimal demo of the problem**
npm run webdriver-update 
npm run webdriver-start
npm run serve.e2e
npm run e2e

**Current behavior**

```
[23:33:01] I/direct - Using ChromeDriver directly...
[23:33:01] I/launcher - Running 1 instances of WebDriver
[23:33:02] E/launcher - Error: ReferenceError: Zone is not defined
    at Object.<anonymous> (/Users/jakepartusch/Documents/angular/angular2-seed-advanced/modules/@angular/core/testing/fake_async.ts:8:34)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jakepartusch/Documents/angular/angular2-seed-advanced/modules/@angular/core/testing.ts:5:3)
    at Module._compile (module.js:541:32)
[23:33:02] E/launcher - Process exited with error code 100
```

**Other information**
Related?
https://github.com/angular/protractor/issues/3181

**Comment by NathanWalker** [comment]
Thanks @JakePartusch! not sure, I'll see what I can find out.

**Comment by NathanWalker** [comment]
Found it, protractor needed this: `require("zone.js/dist/zone-node");`
Thanks again for the report 👍

**Comment by sorakthun** [comment]
@NathanWalker What's your thought on this? https://github.com/angular/protractor/issues/4364
