### ISSUE TITLE
[setup] problem when installing on a second machine

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#93]
hey, 

i followed the steps you described in the setup section.
then i uploaded the changes to my git repo.
after that i cloned the repo on another machine and tried to npm install.
that try gave an error, which says that the file tools/install.js is missing.
i saw in the .gitignore, that you are ignoring that file and so its not going to be uploaded into the repo.

i copied the file manually and after that npm install is running fine. 

so i wanted to ask why you are ignoring the install.js.

**Comment by NathanWalker** [comment]
Actually it's not ignoring it (the opposite):
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/.gitignore#L38

**Comment by NathanWalker** [comment]
The change went in 14 days ago:
https://github.com/NathanWalker/angular2-seed-advanced/commit/dbfc791ed31a7282783269be93bf1b871160568c

It's possible you are working off a version of the seed prior to that commit which may have been ignoring that file which is why you did not have it on yours.

Please ensure you are up to date with latest master:

```
git fetch upstream
git merge upstream/master
```

**Comment by JanOschii** [comment]
Sorry for coming back on this.
I found this file:  " tools/install.js " in the correct folder and its part of .gitignore like you described above.

But if i try:

```
git fetch upstream
git merge upstream/master
```

I get this message:

```
error: The following untracked working tree files would be overwritten by merge:
        tools/install.js
Please move or remove them before you can merge.
Aborting
```

If I use `npm run merge` (which as I understand is the same like git fetch/merge) I get this output in `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'merge' ]
2 info using npm@3.8.8
3 info using node@v6.2.0
4 verbose run-script [ 'premerge', 'merge', 'postmerge' ]
5 info lifecycle angular2-seed-advanced@0.0.0~premerge: angular2-seed-advanced@0.0.0
6 silly lifecycle angular2-seed-advanced@0.0.0~premerge: no script for premerge, continuing
7 info lifecycle angular2-seed-advanced@0.0.0~merge: angular2-seed-advanced@0.0.0
8 verbose lifecycle angular2-seed-advanced@0.0.0~merge: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed-advanced@0.0.0~merge: PATH: ... 
10 verbose lifecycle angular2-seed-advanced@0.0.0~merge: CWD: C:\Users\Admin\.docker.projects\nginx-php-fpm-phalcon\www\front04
11 silly lifecycle angular2-seed-advanced@0.0.0~merge: Args: [ '/d /s /c',
11 silly lifecycle   'git fetch upstream && git merge upstream/master' ]
12 silly lifecycle angular2-seed-advanced@0.0.0~merge: Returned: code: 128  signal: null
13 info lifecycle angular2-seed-advanced@0.0.0~merge: Failed to exec merge script
14 verbose stack Error: angular2-seed-advanced@0.0.0 merge: `git fetch upstream && git merge upstream/master`
14 verbose stack Exit status 128
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed-advanced@0.0.0
16 verbose cwd C:\Users\Admin\.docker.projects\nginx-php-fpm-phalcon\www\front04
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "merge"
19 error node v6.2.0
20 error npm  v3.8.8
21 error code ELIFECYCLE
22 error angular2-seed-advanced@0.0.0 merge: `git fetch upstream && git merge upstream/master`
22 error Exit status 128
23 error Failed at the angular2-seed-advanced@0.0.0 merge script 'git fetch upstream && git merge upstream/master'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed-advanced package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git fetch upstream && git merge upstream/master
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed-advanced
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed-advanced
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by JanOschii** [comment]
That seems to solve this problem:

```
git fetch --all
git reset --hard upstream/master
```

**Comment by NathanWalker** [comment]
Thanks for reporting a proper fix for anyone else that may run into this @JanOschii  👍
